version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  train-model-1:
    docker:
      - image: cimg/python:3.9
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install numpy matplotlib seaborn requests
      - run:
          name: Configure matplotlib
          command: |
            echo "backend: Agg" > matplotlibrc
            export MPLBACKEND=Agg
      - run:
          name: Run training script
          command: python train_model.py
          no_output_timeout: 350m

workflows:
  version: 2
  run-model-training:
    jobs:
      - train-model-1:
          filters:
            branches:
              only:
                - main
